openeyes/OpenEyes

protected/components/Admin.php
protected/views/admin/generic/edit.php

- customView to render
- custom save URL
- custom cancel URL

Several changes in the Admin class edit:

---

protected/controllers/oeadmin/FormularyDrugsController.php

This will fixe issue of OE-5514 and OE-5516

OE-5514 ::  Changed Model Display name.

---

protected/controllers/oeadmin/LeafletFirmController.php

OE-5442 Leaflet firm assign administration v1

---

protected/views/admin/sidebar.php

OE-5402 Admin Menu for Common Systemic Disorders admin

---

protected/controllers/oeadmin/CommonMedicationsController.php
protected/migrations/m150422_140607_medication_common.php
protected/models/CommonMedications.php
protected/views/admin/sidebar.php

it's include one migration script as well.

Feature/oe 5522.v2

---

protected/components/Admin.php
protected/components/ModelSearch.php
protected/views/admin/generic/list.php

- Fixed issue with search within a relational table
- Fixed ordering function: now it works with relational tables and search together

OE-5426 fixes

---

protected/controllers/AdminController.php
protected/modules/OphInBiometry/assets/js/module.js
protected/modules/OphInBiometry/views/default/form_Element_OphInBiometry_Measurement_fields.php
protected/modules/OphInBiometry/views/default/view_Element_OphInBiometry_Selection_fields.php

- setting page for boolean fields was not working - fixed

- calculating delta K and delta K axis in manual Biometry

---

protected/modules/OphCiExamination/migrations/m151110_164012_create_fundus_element.php
protected/modules/OphCiExamination/models/Element_OphCiExamination_Fundus.php
protected/modules/OphCiExamination/views/default/form_Element_OphCiExamination_AnteriorSegment_OEEyeDraw.php
protected/modules/OphCiExamination/views/default/form_Element_OphCiExamination_Fundus.php
protected/modules/OphCiExamination/views/default/form_Element_OphCiExamination_Fundus_OEEyeDraw.php
protected/modules/OphCiExamination/views/default/form_Element_OphCiExamination_Fundus_OEEyeDraw_fields.php
protected/modules/OphCiExamination/views/default/view_Element_OphCiExamination_Fundus.php
protected/modules/OphCiExamination/views/default/view_Element_OphCiExamination_Fundus_OEEyeDraw.php
protected/modules/OphTrOperationnote/controllers/DefaultController.php
protected/modules/OphTrOperationnote/views/default/form_Element_OphTrOperationnote_Cataract_OEEyeDraw.php

These changes bring:
- new doodles to the anterior segment in examination
- new fundus element to examination
- new doodles for op note

New doodles in examination and op note

---

protected/assets/css/dashboard.css
protected/assets/js/dashboard/initOEscape.js
protected/modules/OphCiExamination/controllers/OEScapeDataController.php
protected/views/oescape/vfimages.php

- KOWA image display

---

protected/assets/js/dashboard/initOEscape.js
protected/views/oescape/vfimages.php

- changed colours

---

protected/assets/css/dashboard.css
protected/assets/js/dashboard/initOEscape.js

- added border to colour spots
- added linear line information

- regression chart with fixed yAxis values

---

.gitignore
protected/assets/js/dashboard/initOEscape.js

- design changes for the regression chart
- fixed bug: can select only one coloured dot

- new margins for the left charts

---

protected/assets/css/dashboard.css
protected/assets/js/dashboard/initOEscape.js
protected/views/oescape/vfimages.php

- changed date label in charts

- changed colors

---

protected/assets/css/dashboard.css
protected/assets/css/style.css
protected/assets/sass/openeyes/components/panels/_patient.scss
protected/modules/OphCiExamination/controllers/OEScapeDataController.php
protected/views/patient/_patient_id.php

- updated regression chart width

- clinical summary link

---

protected/components/UserIdentity.php

Code reviewed by Peter Gallagher.

OE-6070 add native-search method to LDAP authentication

---

protected/modules/OphCiExamination/views/default/form_Element_OphCiExamination_CataractSurgicalManagement.php
protected/modules/OphCiExamination/views/default/print_Element_OphCiExamination_CataractSurgicalManagement.php
protected/modules/OphCiExamination/views/default/view_Element_OphCiExamination_CataractSurgicalManagement.php
protected/views/admin/edit_setting.php

Added the flash warning message for the city road and satellite setting

Added the flash message for the city road and satellite setting

---

protected/components/LogoHelper.php
protected/controllers/AdminController.php
protected/views/admin/logo.php
protected/views/print/event_header.php

Logo upload directory changed due to issue on staging

Logo upload directory changed due to issue on staging

---

protected/components/LogoHelper.php
protected/controllers/AdminController.php
protected/models/Logo.php
protected/views/admin/logo.php
protected/views/print/event_header.php

Changed logo file upload directory for live server and changed the extends for Logo model

Logo upload directory changed for live server

---

protected/views/print/event_header.php

PDF print header error

---

protected/controllers/AdminController.php
protected/views/admin/logo.php

Dimensions are mentioned for the logo upload

Dimensions are mentioned for the logo upload

---

protected/components/PatientSearch.php

Altered Regular Expression for Patient Name Search.

OE-6173 - Fixed Patient Search Regular Expression

---

protected/modules/OphCiExamination/views/default/view_Element_OphCiExamination_Allergy.php

Small changes to display functionality.
Changed wording to be in line with other areas relating to Allergies.
Removed table header if No Allergy is the option chosen.

OE-6151 - Fixed wording and display of Non-Allergy selection

---

protected/migrations/m161006_104513_support_hours.php
protected/views/error/error.php
protected/views/error/error403.php
protected/views/error/error404.php
protected/views/error/error500.php
protected/views/error/errorPAS.php
protected/views/error/support.php

Makes the support hours displayed on error pages configurable.
Refactored code in to template to avoid duplication.

OE-6235: Makes support hours configurable

---

protected/modules/OphCoCvi/assets/js/module.js
protected/modules/OphCoCvi/components/OphCoCvi_Manager.php
protected/modules/OphCoCvi/controllers/DefaultController.php
protected/modules/OphCoCvi/migrations/m161102_094326_preferred_language_text.php
protected/modules/OphCoCvi/models/Element_OphCoCvi_ClericalInfo.php
protected/modules/OphCoCvi/models/Element_OphCoCvi_Demographics.php
protected/modules/OphCoCvi/views/default/capture_signatures.php
protected/modules/OphCoCvi/views/default/form_Element_OphCoCvi_ClericalInfo.php
protected/modules/OphCoCvi/views/default/list_filter.php
protected/modules/OphCoCvi/views/default/view_Element_OphCoCvi_ClericalInfo.php
protected/views/profile/signature.php

Multiple issues with eCVI.
1. Extra commas on some addresses on printout
2. Consultants pin not treated as a Password
3. Hospital Name not used on Printout by address
4. MISSING
5. Preferred Language override
6. Extra CVI List Filter option
7. UNKNOWN REQUIREMENTS

OE-6246 - eCVI issues.

---

protected/models/Document.php
protected/modules/OphCoCorrespondence/assets/js/module.js
protected/modules/OphCoCorrespondence/controllers/DefaultController.php
protected/modules/OphCoCorrespondence/migrations/m161115_111104_sign_off_letter.php
protected/modules/OphCoCorrespondence/models/ElementLetter.php
protected/modules/OphCoCorrespondence/views/default/create.php
protected/modules/OphCoCorrespondence/views/default/create_ElementLetter.php
protected/modules/OphCoCorrespondence/views/default/update.php
protected/modules/OphCoCorrespondence/views/default/update_ElementLetter.php
protected/modules/OphCoCorrespondence/views/default/view.php

This disables the print/send button unless the signed off checkbox on the
correspondence is checked.

Disables print/send button unless signed off.

---

protected/modules/OphCiExamination/controllers/DefaultController.php
protected/modules/OphCiExamination/models/Element_OphCiExamination_Dilation.php

Revert "OE-6353"

---

protected/migrations/m170204_085121_add_visibility_field_to_iop.php
protected/migrations/m170204_085917_add_iot_webstar_other.php
protected/modules/OphCiExamination/views/default/form_Element_OphCiExamination_IntraocularPressure_reading.php

Added the instrument 'Webstar-Other' as invisible
Examination form excludes the invisible instruments from dropdown

Added the property 'visible' to IOP instrument table

---

protected/migrations/m170228_190108_ophindnasample_volume_null.php
protected/modules/OphInDnasample/models/Element_OphInDnasample_Sample.php
protected/modules/OphInDnasample/views/default/form_Element_OphInDnasample_Sample.php

- only genetics users are listed in "consented by" field for dna sample

OE-6280 - Genetics - Add missing fields to DNA Sample Event

---

protected/models/Patient.php
protected/modules/OphCiExamination/components/OphCiExamination_API.php
protected/modules/OphCoCorrespondence/components/OphCoCorrespondence_API.php

OE-6503 - Correspondence: 'Other' allergies not displaying real name for [aka] and [alg] shortcodes

---

protected/modules/OphInDnaextraction/assets/js/module.js
protected/modules/OphInDnaextraction/controllers/DefaultController.php
protected/modules/OphInDnaextraction/controllers/DnaExtractionBoxAdminController.php
protected/modules/OphInDnaextraction/models/Element_OphInDnaextraction_DnaExtraction.php
protected/modules/OphInDnaextraction/models/OphInDnaextraction_DnaExtraction_Box.php
protected/modules/OphInDnaextraction/views/default/form_Element_OphInDnaextraction_DnaExtraction.php
protected/modules/OphInDnaextraction/views/default/view_Element_OphInDnaextraction_DnaExtraction.php

…s and fixed "extracted by" field save

OE-6512 - Genetics - DNA extraction issues

---

protected/modules/OphInDnasample/models/Element_OphInDnasample_Sample.php
protected/modules/OphInDnasample/views/default/form_Element_OphInDnasample_Sample.php
protected/modules/OphInDnasample/views/default/view.php
protected/modules/OphInDnasample/views/default/view_Element_OphInDnasample_Sample.php

OE-6544 - Genetics - DNA sample remove "local" field

---

protected/migrations/m170321_183126_predicted_refraction_nullable_in_element_ophtroperationnote_cataract.php
protected/modules/OphTrOperationnote/assets/js/module.js
protected/modules/OphTrOperationnote/models/Element_OphTrOperationnote_Cataract.php
protected/modules/OphTrOperationnote/views/default/form_Element_OphTrOperationnote_Cataract_OEEyeDraw_fields.php

…note event while the posterior chamber not exists

OE-6295 - Unable to record phakomulsification procedure on openeyes

---

protected/modules/OphInDnaextraction/assets/js/module.js
protected/modules/OphInDnaextraction/models/OphInDnaextraction_DnaTests_Transaction.php
protected/modules/OphInDnaextraction/views/default/_dna_test.php
protected/modules/OphInDnaextraction/views/default/form_Element_OphInDnaextraction_DnaExtraction.php

Revert "OE-6545 - Genetics - DNA extraction volume remaining warning"

---

protected/modules/OphInGeneticresults/migrations/m170408_132957_grant_gr_creation_to_lab_users.php

OE-6574 - Genetics - Allow lab users to create Genetic Results events

---

protected/models/Event.php
protected/modules/OphCiExamination/components/ExaminationCreator.php
protected/modules/OphCoMessaging/views/templates/optom.php

OE-6459 - Show optometrist Address on Optom Examination Notes

---

protected/modules/OphCiExamination/components/ExaminationCreator.php
protected/modules/OphCoMessaging/components/MessageCreator.php

OE-6606 - Change messages produced via the community optom portal to be sent to surgeon, not 'Firm' Consultant

---

protected/modules/OphCoCorrespondence/components/OphCoCorrespondence_API.php

Change to get DRSS via practice not patient.

Change to get DRSS via practice not patient.

---

protected/assets/css/new_ui.css
protected/assets/fonts/Roboto/roboto.css
protected/config/core/common.php

Roboto font is now loaded from OE assets

OE-6787 - issues using roboto font with firewalls

---

protected/assets/js/OpenEyes.UI.DiagnosesSearch.js

Change "Change medication" to "Change diagnosis" on diagnosis rename link
